Test fix for MTA Server x64 build error:
cryptopp.lib(cpu.obj) : error LNK2019: unresolved external symbol XGETBV64 referenced in function "void __cdecl CryptoPP::DetectX86Features(void)" (?DetectX86Features@CryptoPP@@YAXXZ) [D:\a\mtasa-blue\mtasa-blue\Build\Deathmatch.vcxproj]
cryptopp.lib(cpu.obj) : error LNK2019: unresolved external symbol CPUID64 referenced in function "bool __cdecl CryptoPP::CpuId(unsigned int,unsigned int,unsigned int * const)" (?CpuId@CryptoPP@@YA_NIIQEAI@Z) [D:\a\mtasa-blue\mtasa-blue\Build\Deathmatch.vcxproj]
..\Bin\server\x64\deathmatch.dll : fatal error LNK1120: 2 unresolved externals [D:\a\mtasa-blue\mtasa-blue\Build\Deathmatch.vcxproj]

Following 7ba2a4c
Due to https://github.com/weidai11/cryptopp/commit/043208515799c06d570d8d6f9b81c324a33832a2