Fix build error caused by zlib upgrade (Addendum to 0f37ac0)
fatal error C1189: #error: ZLIB_VERNUM != PNG_ZLIB_VERNUM "-I (include path) error: see the notes in pngpriv.h"